import express from 'express';
import { auth, isHR } from '../middleware/auth.js';
import Notification from '../models/Notification.js';
import User from '../models/User.js';
import Course from '../models/Course.js';
import Blog from '../models/Blog.js';

const router = express.Router();

router.get('/', auth, async (req, res) => {
  const list = await Notification.find({ toUserId: req.user.userId }).sort({ createdAt: -1 }).limit(50);
  res.json(list);
});

router.patch('/:id/read', auth, async (req, res) => {
  await Notification.findOneAndUpdate({ _id: req.params.id, toUserId: req.user.userId }, { read: true });
  res.json({ ok: true });
});

// Learning: courses + enroll + blogs
router.get('/courses', async (req, res) => {
  const { q, level, skill } = req.query;
  const filter = {};
  
  if (q) {
    const re = new RegExp(q, 'i');
    filter.$or = [{ title: re }, { description: re }, { skills: re }];
  }
  if (level) filter.level = level;
  if (skill) filter.skills = skill;
  
  let courses = await Course.find(filter).sort({ createdAt: -1 });
  
  // Upsert the full sample course catalog (keyed by slug) so every level, price
  // and skill filter in the Courses UI has matching cards even when the
  // collection already contains a few courses.
  if (!q && !level && !skill) {
    const catalog = [
      // Frontend Development (15 courses)
      { slug: 'react-mastery', title: 'React Mastery - From Basics to Advanced', description: 'Complete React ecosystem including Hooks, Context, Redux, and performance optimization', level: 'Intermediate', skills: ['React', 'JavaScript', 'Redux'], priceCoins: 250, isPremium: true, modules: [{ title: 'React Fundamentals', notes: 'Components, Props, State', durationMin: 45 }, { title: 'Hooks Deep Dive', notes: 'useState, useEffect, Custom Hooks', durationMin: 60 }] },
      { slug: 'vue-complete', title: 'Vue 3 Complete Guide', description: 'Master Vue 3 Composition API, Pinia state management, and modern Vue patterns', level: 'Intermediate', skills: ['Vue', 'JavaScript'], priceCoins: 220, isPremium: true, modules: [] },
      { slug: 'angular-advanced', title: 'Angular Enterprise Development', description: 'Build scalable Angular applications with RxJS, NgRx, and advanced patterns', level: 'Advanced', skills: ['Angular', 'TypeScript', 'RxJS'], priceCoins: 280, isPremium: true, modules: [] },
      { slug: 'nextjs-production', title: 'Next.js Production Ready Apps', description: 'SSR, SSG, API routes, deployment strategies, and performance optimization', level: 'Advanced', skills: ['Next.js', 'React', 'TypeScript'], priceCoins: 300, isPremium: true, modules: [] },
      { slug: 'typescript-pro', title: 'TypeScript Pro - Advanced Types', description: 'Generics, conditional types, utility types, and type-level programming', level: 'Advanced', skills: ['TypeScript'], priceCoins: 200, isPremium: true, modules: [] },
      { slug: 'tailwind-design', title: 'Tailwind CSS Design System', description: 'Build beautiful, responsive UIs with Tailwind CSS and design tokens', level: 'Beginner', skills: ['CSS', 'Tailwind'], priceCoins: 100, isPremium: false, modules: [] },
      { slug: 'css-animations', title: 'CSS Animations & Transitions Masterclass', description: 'Create stunning animations with CSS, GSAP, and Framer Motion', level: 'Intermediate', skills: ['CSS', 'JavaScript'], priceCoins: 180, isPremium: true, modules: [] },
      { slug: 'webpack-vite', title: 'Modern Build Tools - Webpack & Vite', description: 'Module bundling, code splitting, and optimization strategies', level: 'Advanced', skills: ['JavaScript', 'Webpack', 'Vite'], priceCoins: 220, isPremium: true, modules: [] },
      { slug: 'pwa-development', title: 'Progressive Web Apps from Scratch', description: 'Service workers, offline support, push notifications, and app-like experience', level: 'Intermediate', skills: ['JavaScript', 'PWA'], priceCoins: 190, isPremium: true, modules: [] },
      { slug: 'web-accessibility', title: 'Web Accessibility (WCAG 2.1)', description: 'Build inclusive applications following ARIA and accessibility best practices', level: 'Intermediate', skills: ['HTML', 'JavaScript', 'Accessibility'], priceCoins: 0, isPremium: false, modules: [] },
      { slug: 'responsive-design', title: 'Responsive Design Patterns', description: 'Mobile-first design, media queries, and responsive typography', level: 'Beginner', skills: ['CSS', 'HTML'], priceCoins: 0, isPremium: false, modules: [] },
      { slug: 'svelte-kit', title: 'SvelteKit Modern Web Development', description: 'Build lightning-fast apps with Svelte and SvelteKit framework', level: 'Intermediate', skills: ['Svelte', 'JavaScript'], priceCoins: 200, isPremium: true, modules: [] },
      { slug: 'graphql-client', title: 'GraphQL Client Development', description: 'Apollo Client, React Query, and GraphQL best practices', level: 'Intermediate', skills: ['GraphQL', 'React', 'TypeScript'], priceCoins: 220, isPremium: true, modules: [] },
      { slug: 'micro-frontends', title: 'Micro-Frontends Architecture', description: 'Module Federation, Webpack 5, and scalable frontend architecture', level: 'Advanced', skills: ['JavaScript', 'Webpack', 'Architecture'], priceCoins: 300, isPremium: true, modules: [] },
      { slug: 'web-components', title: 'Native Web Components', description: 'Custom Elements, Shadow DOM, and reusable component patterns', level: 'Intermediate', skills: ['JavaScript', 'Web Components'], priceCoins: 150, isPremium: false, modules: [] },

      // Backend Development (15 courses)
      { slug: 'nodejs-microservices', title: 'Node.js Microservices Architecture', description: 'Build scalable microservices with Node.js, Docker, and Kubernetes', level: 'Advanced', skills: ['Node.js', 'Docker', 'Kubernetes'], priceCoins: 350, isPremium: true, modules: [] },
      { slug: 'express-restapi', title: 'Express.js REST API Mastery', description: 'Authentication, validation, error handling, and API best practices', level: 'Intermediate', skills: ['Node.js', 'Express.js'], priceCoins: 180, isPremium: true, modules: [] },
      { slug: 'nestjs-enterprise', title: 'NestJS Enterprise Applications', description: 'TypeScript-first backend framework with dependency injection and modularity', level: 'Advanced', skills: ['NestJS', 'TypeScript', 'Node.js'], priceCoins: 300, isPremium: true, modules: [] },
      { slug: 'graphql-server', title: 'GraphQL Server Development', description: 'Apollo Server, schema design, resolvers, and performance optimization', level: 'Intermediate', skills: ['GraphQL', 'Node.js'], priceCoins: 220, isPremium: true, modules: [] },
      { slug: 'python-flask', title: 'Python Flask Web Development', description: 'Build REST APIs and web applications with Flask framework', level: 'Intermediate', skills: ['Python', 'Flask'], priceCoins: 180, isPremium: true, modules: [] },
      { slug: 'django-advanced', title: 'Django Advanced Patterns', description: 'ORM optimization, custom middleware, async views, and Django REST framework', level: 'Advanced', skills: ['Python', 'Django'], priceCoins: 250, isPremium: true, modules: [] },
      { slug: 'fastapi-modern', title: 'FastAPI Modern Python APIs', description: 'Async Python APIs with automatic documentation and type validation', level: 'Intermediate', skills: ['Python', 'FastAPI'], priceCoins: 200, isPremium: true, modules: [] },
      { slug: 'spring-boot', title: 'Spring Boot Microservices', description: 'Java Spring Boot, Spring Cloud, and enterprise application development', level: 'Advanced', skills: ['Java', 'Spring Boot'], priceCoins: 280, isPremium: true, modules: [] },
      { slug: 'golang-backend', title: 'Go Backend Development', description: 'Goroutines, channels, and building high-performance APIs with Go', level: 'Advanced', skills: ['Go', 'Backend'], priceCoins: 280, isPremium: true, modules: [] },
      { slug: 'rust-web', title: 'Rust Web Development', description: 'Build blazing-fast web services with Rust and Actix/Rocket frameworks', level: 'Advanced', skills: ['Rust', 'Backend'], priceCoins: 320, isPremium: true, modules: [] },
      { slug: 'mongodb-mastery', title: 'MongoDB Performance & Scaling', description: 'Aggregation, indexing, sharding, and MongoDB best practices', level: 'Intermediate', skills: ['MongoDB', 'Database'], priceCoins: 200, isPremium: true, modules: [] },
      { slug: 'postgresql-advanced', title: 'PostgreSQL Advanced Techniques', description: 'Query optimization, JSONB, full-text search, and performance tuning', level: 'Advanced', skills: ['PostgreSQL', 'SQL'], priceCoins: 220, isPremium: true, modules: [] },
      { slug: 'redis-caching', title: 'Redis Caching Strategies', description: 'In-memory data structures, pub/sub, and distributed caching patterns', level: 'Intermediate', skills: ['Redis', 'Caching'], priceCoins: 180, isPremium: true, modules: [] },
      { slug: 'rabbitmq-messaging', title: 'RabbitMQ Message Queues', description: 'Asynchronous messaging, work queues, and distributed system patterns', level: 'Intermediate', skills: ['RabbitMQ', 'Messaging'], priceCoins: 200, isPremium: true, modules: [] },
      { slug: 'grpc-apis', title: 'gRPC API Development', description: 'Protocol Buffers, streaming, and high-performance RPC APIs', level: 'Advanced', skills: ['gRPC', 'API'], priceCoins: 250, isPremium: true, modules: [] },

      // Full Stack & DevOps (10 courses)
      { slug: 'mern-mastery', title: 'Full Stack MERN Mastery', description: 'React, Node, Express, Mongo + deployment', level: 'Intermediate', skills: ['React', 'Node.js', 'MongoDB'], priceCoins: 200, isPremium: true, modules: [{ title: 'Intro', notes: 'MERN overview', durationMin: 20 }] },
      { slug: 'docker-kubernetes', title: 'Docker & Kubernetes Orchestration', description: 'Containerization, deployment, scaling, and production-grade K8s', level: 'Advanced', skills: ['Docker', 'Kubernetes', 'DevOps'], priceCoins: 300, isPremium: true, modules: [] },
      { slug: 'aws-architect', title: 'AWS Solutions Architect', description: 'EC2, S3, Lambda, RDS, CloudFormation, and cloud architecture patterns', level: 'Advanced', skills: ['AWS', 'Cloud'], priceCoins: 350, isPremium: true, modules: [] },
      { slug: 'terraform-iac', title: 'Terraform Infrastructure as Code', description: 'Multi-cloud provisioning, state management, and IaC best practices', level: 'Advanced', skills: ['Terraform', 'DevOps'], priceCoins: 280, isPremium: true, modules: [] },
      { slug: 'cicd-pipelines', title: 'CI/CD Pipelines with GitHub Actions', description: 'Automated testing, deployment workflows, and GitOps practices', level: 'Intermediate', skills: ['CI/CD', 'DevOps'], priceCoins: 200, isPremium: true, modules: [] },
      { slug: 'linux-sysadmin', title: 'Linux System Administration', description: 'Shell scripting, process management, networking, and security', level: 'Intermediate', skills: ['Linux', 'DevOps'], priceCoins: 180, isPremium: false, modules: [] },
      { slug: 'nginx-optimization', title: 'Nginx Load Balancing & Optimization', description: 'Reverse proxy, caching, SSL/TLS, and performance tuning', level: 'Intermediate', skills: ['Nginx', 'DevOps'], priceCoins: 150, isPremium: true, modules: [] },
      { slug: 'monitoring-observability', title: 'Monitoring & Observability Stack', description: 'Prometheus, Grafana, ELK stack, and distributed tracing', level: 'Advanced', skills: ['Monitoring', 'DevOps'], priceCoins: 280, isPremium: true, modules: [] },
      { slug: 'security-hardening', title: 'Application Security & Hardening', description: 'OWASP Top 10, secure coding, penetration testing basics', level: 'Advanced', skills: ['Security', 'DevOps'], priceCoins: 300, isPremium: true, modules: [] },
      { slug: 'serverless-aws', title: 'Serverless Architecture on AWS', description: 'Lambda, API Gateway, DynamoDB, and serverless patterns', level: 'Advanced', skills: ['AWS', 'Serverless'], priceCoins: 280, isPremium: true, modules: [] },

      // Data Science & ML (10 courses)
      { slug: 'python-data-science', title: 'Python for Data Science', description: 'NumPy, Pandas, Matplotlib, and data analysis workflows', level: 'Beginner', skills: ['Python', 'Data Science'], priceCoins: 0, isPremium: false, modules: [] },
      { slug: 'machine-learning', title: 'Machine Learning Fundamentals', description: 'Supervised/unsupervised learning, scikit-learn, and model evaluation', level: 'Intermediate', skills: ['Python', 'ML'], priceCoins: 250, isPremium: true, modules: [] },
      { slug: 'deep-learning', title: 'Deep Learning with PyTorch', description: 'Neural networks, CNNs, RNNs, and transfer learning', level: 'Advanced', skills: ['Python', 'PyTorch', 'Deep Learning'], priceCoins: 320, isPremium: true, modules: [] },
      { slug: 'tensorflow-production', title: 'TensorFlow Production ML', description: 'Model deployment, TensorFlow Serving, and MLOps', level: 'Advanced', skills: ['TensorFlow', 'ML', 'MLOps'], priceCoins: 300, isPremium: true, modules: [] },
      { slug: 'nlp-transformers', title: 'NLP with Transformers', description: 'BERT, GPT, fine-tuning, and modern NLP techniques', level: 'Advanced', skills: ['Python', 'NLP', 'Transformers'], priceCoins: 350, isPremium: true, modules: [] },
      { slug: 'computer-vision', title: 'Computer Vision with OpenCV', description: 'Image processing, object detection, and real-time CV applications', level: 'Intermediate', skills: ['Python', 'OpenCV', 'Computer Vision'], priceCoins: 280, isPremium: true, modules: [] },
      { slug: 'data-engineering', title: 'Data Engineering Pipelines', description: 'ETL workflows, Airflow, Spark, and data warehouse design', level: 'Advanced', skills: ['Python', 'Airflow', 'Spark'], priceCoins: 300, isPremium: true, modules: [] },
      { slug: 'sql-analytics', title: 'SQL for Data Analytics', description: 'Window functions, CTEs, query optimization, and analytical patterns', level: 'Intermediate', skills: ['SQL', 'Analytics'], priceCoins: 150, isPremium: false, modules: [] },
      { slug: 'tableau-visualization', title: 'Tableau Data Visualization', description: 'Interactive dashboards, calculated fields, and storytelling with data', level: 'Beginner', skills: ['Tableau', 'Analytics'], priceCoins: 180, isPremium: true, modules: [] },
      { slug: 'power-bi', title: 'Power BI Business Intelligence', description: 'DAX formulas, Power Query, and enterprise reporting', level: 'Intermediate', skills: ['Power BI', 'Analytics'], priceCoins: 200, isPremium: true, modules: [] },

      // Soft Skills & Career (5 courses)
      { slug: 'system-design', title: 'System Design for Interviews', description: 'Scalability, caching, load balancing, and distributed systems', level: 'Advanced', skills: ['System Design', 'Interviews'], priceCoins: 280, isPremium: true, modules: [] },
      { slug: 'dsa-basics', title: 'Data Structures & Algorithms', description: 'Arrays, maps, two pointers, and problem-solving techniques', level: 'Beginner', skills: ['DSA'], priceCoins: 0, isPremium: false, modules: [] },
      { slug: 'dsa-advanced', title: 'Advanced DSA & Competitive Programming', description: 'Trees, graphs, DP, backtracking, and contest strategies', level: 'Advanced', skills: ['DSA'], priceCoins: 250, isPremium: true, modules: [] },
      { slug: 'tech-leadership', title: 'Tech Leadership & Management', description: 'Team building, project planning, and engineering management', level: 'Advanced', skills: ['Leadership', 'Management'], priceCoins: 220, isPremium: true, modules: [] },
      { slug: 'freelancing-business', title: 'Freelancing & Tech Business', description: 'Client acquisition, pricing, contracts, and building a tech business', level: 'Beginner', skills: ['Business', 'Freelancing'], priceCoins: 150, isPremium: false, modules: [] },
      // Starter courses that guarantee every Popular Skills filter resolves
      { slug: 'react-for-beginners', title: 'React for Beginners', description: 'Components, props, state, and building your first React application', level: 'Beginner', skills: ['React', 'JavaScript'], priceCoins: 0, isPremium: false, modules: [] },
      { slug: 'modern-javascript', title: 'Modern JavaScript (ES2024)', description: 'Modules, closures, async patterns, iterators, and modern language features', level: 'Beginner', skills: ['JavaScript'], priceCoins: 0, isPremium: false, modules: [] },
      { slug: 'typescript-basics', title: 'TypeScript Basics', description: 'Types, interfaces, unions, and migrating a JavaScript codebase safely', level: 'Beginner', skills: ['TypeScript'], priceCoins: 0, isPremium: false, modules: [] },
      { slug: 'nodejs-api-foundations', title: 'Node.js API Foundations', description: 'Build REST APIs with Express, middleware, validation, and error handling', level: 'Beginner', skills: ['Node.js', 'Express.js'], priceCoins: 0, isPremium: false, modules: [] },
      { slug: 'python-for-developers', title: 'Python for Developers', description: 'Syntax, data structures, virtual environments, and packaging', level: 'Beginner', skills: ['Python'], priceCoins: 0, isPremium: false, modules: [] },
      { slug: 'modern-css-layouts', title: 'Modern CSS Layouts', description: 'Flexbox, Grid, container queries, and responsive design patterns', level: 'Beginner', skills: ['CSS'], priceCoins: 0, isPremium: false, modules: [] },
      { slug: 'docker-for-developers', title: 'Docker for Developers', description: 'Images, containers, volumes, networking, and multi-stage builds', level: 'Beginner', skills: ['Docker', 'DevOps'], priceCoins: 0, isPremium: false, modules: [] },
      { slug: 'aws-cloud-practitioner', title: 'AWS Cloud Practitioner Essentials', description: 'Core AWS services, IAM, networking, storage, and cost management', level: 'Beginner', skills: ['AWS', 'Cloud'], priceCoins: 0, isPremium: false, modules: [] },
      { slug: 'mongodb-atlas-practice', title: 'MongoDB Atlas in Practice', description: 'Data modelling, aggregation pipeline, indexes, and Atlas operations', level: 'Beginner', skills: ['MongoDB', 'Database'], priceCoins: 0, isPremium: false, modules: [] },
      { slug: 'postgresql-essentials', title: 'PostgreSQL Essentials', description: 'Schema design, indexing, transactions, and query tuning in Postgres', level: 'Intermediate', skills: ['PostgreSQL', 'SQL'], priceCoins: 0, isPremium: false, modules: [] },
      { slug: 'data-science-with-python', title: 'Data Science with Python', description: 'NumPy, pandas, exploratory analysis, and your first predictive model', level: 'Beginner', skills: ['Data Science', 'Python'], priceCoins: 0, isPremium: false, modules: [] },
      { slug: 'machine-learning-fundamentals', title: 'Machine Learning Fundamentals', description: 'Supervised and unsupervised learning, model evaluation, and ML pipelines', level: 'Beginner', skills: ['Machine Learning', 'Python'], priceCoins: 0, isPremium: false, modules: [] },
      { slug: 'machine-learning-in-production', title: 'Machine Learning in Production', description: 'Feature stores, model serving, monitoring, and MLOps workflows', level: 'Advanced', skills: ['Machine Learning', 'MLOps'], priceCoins: 300, isPremium: true, modules: [] },
    ];

    const existingSlugs = new Set((await Course.find({}, 'slug')).map((c) => c.slug));
    const missing = catalog.filter((c) => !existingSlugs.has(c.slug));
    if (missing.length) {
      await Course.insertMany(missing);
      courses = await Course.find(filter).sort({ createdAt: -1 });
    }
  }
  
  res.json(courses);
});

router.post('/courses/:slug/enroll', auth, async (req, res) => {
  const course = await Course.findOne({ slug: req.params.slug });
  if (!course) return res.status(404).json({ message: 'Course not found' });
  const user = await User.findById(req.user.userId);
  if (user.enrolledCourses.some((e) => e.courseId === course.slug)) return res.json({ message: 'Already enrolled' });
  if ((course.priceCoins || 0) > (user.skillCoins || 0)) return res.status(400).json({ message: 'Not enough Skill Coins' });
  user.skillCoins -= course.priceCoins || 0;
  user.enrolledCourses.push({ courseId: course.slug, enrolledAt: new Date() });
  await user.save();
  res.json({ message: 'Enrolled', coins: user.skillCoins });
});

router.get('/blogs', async (req, res) => {
  const { q, skill, category } = req.query;
  const filter = {};
  
  if (q) {
    const re = new RegExp(q, 'i');
    filter.$or = [{ title: re }, { excerpt: re }, { content: re }];
  }
  if (skill) filter.skills = skill;
  if (category) filter.category = category;
  
  let blogs = await Blog.find(filter).sort({ createdAt: -1 }).limit(200);
  
  // Upsert the full sample blog catalog (keyed by slug) so every Popular Topic
  // (skill) and Category filter in the Blog UI has matching articles even when
  // the collection already contains a few posts.
  if (!q && !skill && !category) {
    const catalog = [
      // Frontend Development Blogs (15)
      { slug: 'react-hooks-guide', title: 'React Hooks Deep Dive', category: 'React', excerpt: 'Master useState, useEffect, useContext, and custom hooks with real-world examples', skills: ['React', 'JavaScript'], readMin: 8, content: 'React Hooks revolutionized how we write components. This guide covers all built-in hooks, performance optimization with useMemo and useCallback, and patterns for building custom hooks that encapsulate reusable logic.\n\nReference: https://react.dev/reference/react' },
      { slug: 'typescript-generics', title: 'TypeScript Generics Explained', category: 'TypeScript', excerpt: 'From basic type parameters to advanced conditional types and mapped types', skills: ['TypeScript'], readMin: 10, content: 'Generics enable you to write flexible, reusable code while maintaining type safety. Learn how to write generic functions, classes, and interfaces, and explore utility types like Pick, Omit, and ReturnType.\n\nReference: https://www.typescriptlang.org/docs/handbook/2/generics.html' },
      { slug: 'css-grid-mastery', title: 'CSS Grid Layout Mastery', category: 'CSS', excerpt: 'Build complex responsive layouts with CSS Grid and modern layout techniques', skills: ['CSS'], readMin: 12, content: 'CSS Grid provides a two-dimensional layout system. Master grid-template-areas, auto-placement, and alignment properties to create magazine-style layouts and responsive designs.\n\nReference: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout' },
      { slug: 'vue-composition-api', title: 'Vue 3 Composition API Patterns', category: 'Vue', excerpt: 'Organize logic with composables and leverage reactivity primitives', skills: ['Vue', 'JavaScript'], readMin: 9, content: 'The Composition API offers better logic reuse and TypeScript support. Learn how to structure components with setup(), create composables, and use ref, reactive, and computed effectively.\n\nReference: https://vuejs.org/guide/extras/composition-api-faq.html' },
      { slug: 'nextjs-app-router', title: 'Next.js App Router Complete Guide', category: 'Next.js', excerpt: 'Server Components, streaming, and the new App directory architecture', skills: ['Next.js', 'React'], readMin: 15, content: 'The App Router introduces React Server Components to Next.js. Explore server and client components, streaming with Suspense, route groups, and incremental static regeneration (ISR).\n\nReference: https://nextjs.org/docs/app' },
      { slug: 'web-performance', title: 'Web Performance Optimization Checklist', category: 'Performance', excerpt: 'Core Web Vitals, code splitting, lazy loading, and rendering strategies', skills: ['JavaScript', 'Performance'], readMin: 11, content: 'Improve LCP, FID, and CLS with practical techniques: optimize images with WebP and AVIF, implement code splitting, defer non-critical JavaScript, and use intersection observer for lazy loading.\n\nReference: https://web.dev/vitals/' },
      { slug: 'pwa-offline-first', title: 'Progressive Web Apps: Offline-First Strategy', category: 'PWA', excerpt: 'Service workers, caching strategies, and background sync', skills: ['JavaScript', 'PWA'], readMin: 13, content: 'Build resilient web apps that work offline. Implement service worker caching strategies (cache-first, network-first, stale-while-revalidate), background sync, and push notifications.\n\nReference: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps' },
      { slug: 'tailwind-design-system', title: 'Building a Design System with Tailwind CSS', category: 'CSS', excerpt: 'Custom themes, design tokens, and component patterns', skills: ['CSS', 'Tailwind'], readMin: 10, content: 'Extend Tailwind with custom colors, spacing, and typography. Create reusable component classes with @apply, configure dark mode, and maintain consistency across your design system.\n\nReference: https://tailwindcss.com/docs/theme' },
      { slug: 'svelte-reactivity', title: 'Svelte Reactivity Model Explained', category: 'Svelte', excerpt: 'How Svelte compiles reactive statements and stores', skills: ['Svelte', 'JavaScript'], readMin: 8, content: 'Svelte compiles reactive statements at build time, eliminating the need for a virtual DOM. Understand $: syntax, writable and derived stores, and how SvelteKit handles server-side reactivity.\n\nReference: https://svelte.dev/docs/svelte-components' },
      { slug: 'micro-frontends-patterns', title: 'Micro-Frontends Architecture Patterns', category: 'Architecture', excerpt: 'Module Federation, Web Components, and integration strategies', skills: ['JavaScript', 'Architecture'], readMin: 14, content: 'Scale frontend development with micro-frontends. Compare integration approaches: iframes, Webpack Module Federation, single-spa, and Web Components. Discuss shared dependencies and versioning.\n\nReference: https://martinfowler.com/articles/micro-frontends.html' },
      { slug: 'graphql-apollo-client', title: 'GraphQL with Apollo Client', category: 'GraphQL', excerpt: 'Queries, mutations, caching, and optimistic UI updates', skills: ['GraphQL', 'React'], readMin: 12, content: 'Apollo Client provides a complete state management solution for GraphQL apps. Learn query and mutation patterns, normalized caching, pagination, and optimistic responses for instant UI feedback.\n\nReference: https://www.apollographql.com/docs/react/' },
      { slug: 'web-components-standards', title: 'Native Web Components in 2024', category: 'Web Components', excerpt: 'Custom Elements, Shadow DOM, and framework-agnostic components', skills: ['JavaScript', 'Web Components'], readMin: 10, content: 'Build reusable components with Web Standards. Create Custom Elements, use Shadow DOM for encapsulation, leverage HTML templates, and share components across frameworks.\n\nReference: https://developer.mozilla.org/en-US/docs/Web/Web_Components' },
      { slug: 'react-server-components', title: 'Understanding React Server Components', category: 'React', excerpt: 'Zero-bundle React components that run only on the server', skills: ['React', 'Next.js'], readMin: 11, content: 'React Server Components render exclusively on the server, reducing bundle size and improving initial load time. Explore the difference between Server and Client Components, data fetching patterns, and composition.\n\nReference: https://react.dev/blog/2023/03/22/react-labs-what-we-have-been-working-on-march-2023' },
      { slug: 'frontend-testing', title: 'Frontend Testing Strategy: Unit, Integration, E2E', category: 'Testing', excerpt: 'Jest, React Testing Library, Playwright, and testing best practices', skills: ['JavaScript', 'Testing'], readMin: 13, content: 'Build confidence with a comprehensive testing strategy. Write unit tests with Jest, integration tests with React Testing Library, and end-to-end tests with Playwright or Cypress. Follow the testing pyramid.\n\nReference: https://testing-library.com/docs/react-testing-library/intro/' },
      { slug: 'accessibility-wcag', title: 'Web Accessibility: WCAG 2.1 AA Compliance', category: 'Accessibility', excerpt: 'ARIA attributes, keyboard navigation, and screen reader support', skills: ['HTML', 'Accessibility'], readMin: 12, content: 'Build inclusive web applications. Implement semantic HTML, ARIA roles and properties, keyboard navigation, focus management, and color contrast. Test with screen readers like NVDA and VoiceOver.\n\nReference: https://www.w3.org/WAI/WCAG21/quickref/' },

      // Backend Development Blogs (15)
      { slug: 'nodejs-best-practices', title: 'Node.js Best Practices 2024', category: 'Node.js', excerpt: 'Security, performance, and scalability patterns for production Node.js apps', skills: ['Node.js'], readMin: 12, content: 'Building robust Node.js applications requires attention to error handling, async patterns, dependency management, and security. Use ESLint, Prettier, and follow the Node.js Best Practices guide. Implement health checks, structured logging with Winston or Pino, and rate limiting.\n\nReference: https://nodejs.org/en/docs/guides/' },
      { slug: 'express-middleware-patterns', title: 'Express.js Middleware Patterns', category: 'Express.js', excerpt: 'Error handling, authentication, validation, and custom middleware', skills: ['Node.js', 'Express.js'], readMin: 9, content: 'Middleware is the heart of Express applications. Build authentication middleware with JWT, implement request validation with Joi or Zod, create error-handling middleware, and compose middleware for clean route definitions.\n\nReference: https://expressjs.com/en/guide/using-middleware.html' },
      { slug: 'restapi-design', title: 'RESTful API Design Principles', category: 'API', excerpt: 'Resource naming, HTTP methods, status codes, and versioning', skills: ['API', 'Backend'], readMin: 10, content: 'Design intuitive, predictable REST APIs. Follow RESTful conventions for resource URLs, use appropriate HTTP methods (GET, POST, PUT, PATCH, DELETE), return meaningful status codes, implement HATEOAS, and version your API.\n\nReference: https://restfulapi.net/' },
      { slug: 'jwt-authentication', title: 'JWT Authentication & Authorization', category: 'Security', excerpt: 'Token-based auth, refresh tokens, and secure session management', skills: ['Security', 'Node.js'], readMin: 11, content: 'Implement secure authentication with JSON Web Tokens. Generate access and refresh tokens, store refresh tokens securely, handle token expiration, and implement role-based access control (RBAC).\n\nReference: https://jwt.io/introduction' },
      { slug: 'graphql-schema-design', title: 'GraphQL Schema Design Best Practices', category: 'GraphQL', excerpt: 'Resolvers, data loaders, and avoiding N+1 queries', skills: ['GraphQL', 'Backend'], readMin: 13, content: 'Design efficient GraphQL schemas. Structure types and queries logically, implement DataLoader to batch and cache database queries, handle errors gracefully, and optimize resolver performance.\n\nReference: https://graphql.org/learn/best-practices/' },
      { slug: 'database-indexing', title: 'Database Indexing Strategies', category: 'Database', excerpt: 'B-tree, hash, and composite indexes for query optimization', skills: ['SQL', 'Database'], readMin: 12, content: 'Indexes dramatically improve query performance. Understand B-tree and hash indexes, create composite indexes for multi-column queries, analyze query plans with EXPLAIN, and balance read performance vs write overhead.\n\nReference: https://use-the-index-luke.com/' },
      { slug: 'mongodb-aggregation', title: 'MongoDB Aggregation Pipeline Mastery', category: 'MongoDB', excerpt: '$match, $group, $lookup, and complex data transformations', skills: ['MongoDB', 'Database'], readMin: 11, content: 'The aggregation pipeline transforms and analyzes data. Master stages like $match, $group, $project, $lookup (joins), $unwind, and $facet for complex analytics and reporting queries.\n\nReference: https://www.mongodb.com/docs/manual/aggregation/' },
      { slug: 'caching-strategies', title: 'Caching Strategies with Redis', category: 'Redis', excerpt: 'Cache-aside, write-through, and distributed caching patterns', skills: ['Redis', 'Caching'], readMin: 10, content: 'Reduce database load with strategic caching. Implement cache-aside, read-through, and write-through patterns with Redis. Use TTL for expiration, invalidate stale data, and handle cache stampede.\n\nReference: https://redis.io/docs/manual/patterns/' },
      { slug: 'microservices-communication', title: 'Microservices Communication Patterns', category: 'Microservices', excerpt: 'Synchronous REST/gRPC vs asynchronous messaging with RabbitMQ/Kafka', skills: ['Microservices', 'Architecture'], readMin: 14, content: 'Microservices communicate via REST, gRPC, or message queues. Compare synchronous (HTTP, gRPC) vs asynchronous (RabbitMQ, Kafka) approaches. Implement circuit breakers, retries, and saga patterns for distributed transactions.\n\nReference: https://microservices.io/patterns/communication-style/messaging.html' },
      { slug: 'docker-best-practices', title: 'Docker Best Practices for Production', category: 'Docker', excerpt: 'Multi-stage builds, layer caching, and security hardening', skills: ['Docker', 'DevOps'], readMin: 10, content: 'Optimize Docker images with multi-stage builds, minimize layer count, use .dockerignore, run as non-root user, scan for vulnerabilities with Trivy, and implement health checks.\n\nReference: https://docs.docker.com/develop/dev-best-practices/' },
      { slug: 'kubernetes-deployments', title: 'Kubernetes Deployments & Services', category: 'Kubernetes', excerpt: 'Rolling updates, health checks, and service discovery', skills: ['Kubernetes', 'DevOps'], readMin: 13, content: 'Deploy applications on Kubernetes with Deployments, ReplicaSets, and Services. Configure rolling updates, health probes (liveness and readiness), resource limits, and horizontal pod autoscaling.\n\nReference: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/' },
      { slug: 'api-rate-limiting', title: 'API Rate Limiting & Throttling', category: 'API', excerpt: 'Token bucket, leaky bucket, and sliding window algorithms', skills: ['API', 'Backend'], readMin: 9, content: 'Protect your API from abuse with rate limiting. Implement token bucket or sliding window algorithms, use Redis for distributed rate limiting, and communicate limits via HTTP headers (X-RateLimit-*).\n\nReference: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers' },
      { slug: 'logging-monitoring', title: 'Logging & Monitoring for Node.js', category: 'DevOps', excerpt: 'Structured logging, centralized logs, and observability', skills: ['Node.js', 'DevOps'], readMin: 11, content: 'Implement structured logging with Winston or Pino. Send logs to centralized systems (ELK, Datadog, CloudWatch). Add tracing with OpenTelemetry and monitor metrics with Prometheus.\n\nReference: https://www.datadoghq.com/knowledge-center/application-logging/' },
      { slug: 'sql-optimization', title: 'SQL Query Optimization Techniques', category: 'SQL', excerpt: 'EXPLAIN plans, index hints, and query refactoring', skills: ['SQL', 'Database'], readMin: 12, content: 'Optimize slow queries by analyzing EXPLAIN plans. Avoid SELECT *, use covering indexes, refactor subqueries to JOINs, and leverage database-specific features like PostgreSQL CTEs or MySQL query cache.\n\nReference: https://www.postgresql.org/docs/current/performance-tips.html' },
      { slug: 'event-driven-architecture', title: 'Event-Driven Architecture with Kafka', category: 'Architecture', excerpt: 'Producers, consumers, topics, and event sourcing patterns', skills: ['Kafka', 'Architecture'], readMin: 14, content: 'Build scalable event-driven systems with Apache Kafka. Implement producers and consumers, partition topics for parallelism, and explore event sourcing and CQRS patterns for eventual consistency.\n\nReference: https://kafka.apache.org/documentation/' },

      // DevOps & Cloud Blogs (10)
      { slug: 'cicd-github-actions', title: 'CI/CD Pipelines with GitHub Actions', category: 'CI/CD', excerpt: 'Automated testing, deployment, and workflow best practices', skills: ['CI/CD', 'DevOps'], readMin: 10, content: 'Automate your development workflow with GitHub Actions. Create workflows for testing, building, and deploying applications. Use matrix builds for multi-environment testing and secrets for secure credentials.\n\nReference: https://docs.github.com/en/actions' },
      { slug: 'terraform-infrastructure', title: 'Infrastructure as Code with Terraform', category: 'Terraform', excerpt: 'Modules, state management, and multi-cloud provisioning', skills: ['Terraform', 'DevOps'], readMin: 13, content: 'Provision infrastructure declaratively with Terraform. Create reusable modules, manage state with remote backends (S3, Terraform Cloud), and implement GitOps workflows for infrastructure changes.\n\nReference: https://developer.hashicorp.com/terraform/docs' },
      { slug: 'aws-lambda-serverless', title: 'AWS Lambda Serverless Patterns', category: 'AWS', excerpt: 'Event-driven functions, cold starts, and cost optimization', skills: ['AWS', 'Serverless'], readMin: 11, content: 'Build serverless applications with AWS Lambda. Optimize for cold starts with provisioned concurrency, implement event-driven architectures with EventBridge, and monitor with X-Ray and CloudWatch.\n\nReference: https://docs.aws.amazon.com/lambda/latest/dg/welcome.html' },
      { slug: 'prometheus-grafana', title: 'Monitoring with Prometheus & Grafana', category: 'Monitoring', excerpt: 'Metrics collection, alerting, and dashboard creation', skills: ['Prometheus', 'Grafana'], readMin: 12, content: 'Instrument applications with Prometheus metrics. Create custom dashboards in Grafana, set up alerting rules, and use exporters for system and application monitoring.\n\nReference: https://prometheus.io/docs/introduction/overview/' },
      { slug: 'nginx-reverse-proxy', title: 'Nginx as a Reverse Proxy & Load Balancer', category: 'Nginx', excerpt: 'SSL termination, caching, and high-availability setups', skills: ['Nginx', 'DevOps'], readMin: 9, content: 'Configure Nginx for reverse proxying, SSL/TLS termination, load balancing across backend servers, and caching static assets. Implement rate limiting and security headers.\n\nReference: https://nginx.org/en/docs/' },
      { slug: 'security-owasp', title: 'OWASP Top 10 Security Vulnerabilities', category: 'Security', excerpt: 'SQL injection, XSS, CSRF, and secure coding practices', skills: ['Security'], readMin: 14, content: 'Protect applications from common vulnerabilities. Prevent SQL injection with parameterized queries, XSS with input sanitization, CSRF with tokens, and implement security headers (CSP, HSTS).\n\nReference: https://owasp.org/www-project-top-ten/' },
      { slug: 'linux-performance', title: 'Linux Performance Tuning', category: 'Linux', excerpt: 'CPU, memory, disk I/O, and network optimization', skills: ['Linux', 'DevOps'], readMin: 11, content: 'Diagnose and optimize Linux system performance. Use top, htop, iotop, and vmstat for monitoring. Tune kernel parameters, optimize disk I/O with schedulers, and profile applications with perf.\n\nReference: https://www.brendangregg.com/linuxperf.html' },
      { slug: 'elk-stack-logging', title: 'ELK Stack for Centralized Logging', category: 'Logging', excerpt: 'Elasticsearch, Logstash, Kibana for log aggregation', skills: ['ELK', 'DevOps'], readMin: 12, content: 'Aggregate logs from multiple sources with the ELK stack. Ship logs with Filebeat, parse and transform with Logstash, store in Elasticsearch, and visualize with Kibana dashboards.\n\nReference: https://www.elastic.co/guide/index.html' },
      { slug: 'kubernetes-networking', title: 'Kubernetes Networking Fundamentals', category: 'Kubernetes', excerpt: 'Pods, Services, Ingress, and network policies', skills: ['Kubernetes', 'Networking'], readMin: 13, content: 'Understand Kubernetes networking model. Configure Services (ClusterIP, NodePort, LoadBalancer), expose applications with Ingress controllers, and secure communication with Network Policies.\n\nReference: https://kubernetes.io/docs/concepts/services-networking/' },
      { slug: 'gitops-argocd', title: 'GitOps with ArgoCD', category: 'GitOps', excerpt: 'Declarative continuous delivery for Kubernetes', skills: ['GitOps', 'Kubernetes'], readMin: 10, content: 'Implement GitOps workflows with ArgoCD. Sync Kubernetes manifests from Git repositories, automate deployments, and rollback changes declaratively.\n\nReference: https://argo-cd.readthedocs.io/en/stable/' },

      // Data Science & ML Blogs (10)
      { slug: 'pandas-data-analysis', title: 'Pandas for Data Analysis', category: 'Data Science', excerpt: 'DataFrames, groupby, merge, and time series analysis', skills: ['Python', 'Pandas'], readMin: 11, content: 'Master data manipulation with Pandas. Load and clean data, perform groupby aggregations, merge and join DataFrames, handle missing values, and analyze time series data.\n\nReference: https://pandas.pydata.org/docs/user_guide/index.html' },
      { slug: 'ml-model-training', title: 'Machine Learning Model Training Pipeline', category: 'Machine Learning', excerpt: 'Data preprocessing, feature engineering, and model evaluation', skills: ['Python', 'ML'], readMin: 13, content: 'Build end-to-end ML pipelines. Preprocess data with scikit-learn pipelines, engineer features, split train/validation/test sets, train models, tune hyperparameters with grid search, and evaluate with cross-validation.\n\nReference: https://scikit-learn.org/stable/modules/pipeline.html' },
      { slug: 'pytorch-neural-networks', title: 'Building Neural Networks with PyTorch', category: 'Deep Learning', excerpt: 'Tensors, autograd, custom layers, and training loops', skills: ['Python', 'PyTorch'], readMin: 14, content: 'Implement deep learning models with PyTorch. Define custom nn.Module classes, use autograd for automatic differentiation, train with optimizers and loss functions, and save/load model checkpoints.\n\nReference: https://pytorch.org/tutorials/' },
      { slug: 'transformers-nlp', title: 'Transformers for NLP Tasks', category: 'NLP', excerpt: 'BERT, GPT, fine-tuning, and Hugging Face library', skills: ['Python', 'NLP'], readMin: 12, content: 'Use pre-trained transformers for text classification, named entity recognition, and question answering. Fine-tune models with Hugging Face Transformers library and deploy with TorchServe.\n\nReference: https://huggingface.co/docs/transformers/index' },
      { slug: 'computer-vision-opencv', title: 'Computer Vision with OpenCV', category: 'Computer Vision', excerpt: 'Image processing, object detection, and real-time video', skills: ['Python', 'OpenCV'], readMin: 11, content: 'Process images and video with OpenCV. Apply filters, detect edges, perform object detection with YOLO or SSD, track objects in video streams, and optimize for real-time performance.\n\nReference: https://docs.opencv.org/4.x/' },
      { slug: 'mlops-model-deployment', title: 'MLOps: Deploying ML Models to Production', category: 'MLOps', excerpt: 'Model serving, monitoring, and retraining pipelines', skills: ['MLOps', 'Python'], readMin: 13, content: 'Deploy ML models with FastAPI, Flask, or TensorFlow Serving. Containerize with Docker, monitor model performance and drift, automate retraining pipelines, and implement A/B testing.\n\nReference: https://ml-ops.org/' },
      { slug: 'sql-for-data-science', title: 'SQL for Data Science', category: 'SQL', excerpt: 'Window functions, CTEs, and analytical queries', skills: ['SQL', 'Data Science'], readMin: 10, content: 'Write advanced SQL for data analysis. Use window functions (ROW_NUMBER, RANK, LAG), CTEs for readable queries, aggregate functions, and JOINs to combine data from multiple tables.\n\nReference: https://mode.com/sql-tutorial/' },
      { slug: 'data-visualization', title: 'Data Visualization Best Practices', category: 'Data Science', excerpt: 'Choosing charts, color theory, and storytelling with data', skills: ['Data Visualization'], readMin: 9, content: 'Create effective visualizations with Matplotlib, Seaborn, or Plotly. Choose appropriate chart types (bar, line, scatter, heatmap), apply color theory, and tell stories with data.\n\nReference: https://matplotlib.org/stable/tutorials/index.html' },
      { slug: 'apache-spark', title: 'Big Data Processing with Apache Spark', category: 'Data Engineering', excerpt: 'RDDs, DataFrames, and distributed data processing', skills: ['Spark', 'Python'], readMin: 12, content: 'Process large datasets with Apache Spark. Use DataFrames and Spark SQL for structured data, implement transformations and actions, optimize with partitioning and caching, and deploy on clusters.\n\nReference: https://spark.apache.org/docs/latest/' },
      { slug: 'feature-engineering', title: 'Feature Engineering for Machine Learning', category: 'Machine Learning', excerpt: 'Encoding, scaling, polynomial features, and domain knowledge', skills: ['ML', 'Python'], readMin: 11, content: 'Improve model performance with feature engineering. Encode categorical variables (one-hot, label, target encoding), scale numerical features, create polynomial features, and leverage domain knowledge.\n\nReference: https://scikit-learn.org/stable/modules/preprocessing.html' },
      // Articles that guarantee every Popular Topic (skill) filter resolves
      { slug: 'postgresql-performance-tuning', title: 'PostgreSQL Performance Tuning', category: 'PostgreSQL', excerpt: 'EXPLAIN ANALYZE, indexing strategy, and memory tuning for Postgres', skills: ['PostgreSQL', 'SQL'], readMin: 12, content: 'Indexing strategy drives most PostgreSQL performance wins. Read EXPLAIN ANALYZE plans, add covering and partial indexes, avoid sequential scans on large tables, keep statistics fresh with ANALYZE, and tune work_mem and shared_buffers for your workload. Reference: https://www.postgresql.org/docs/current/performance-tips.html' },
      { slug: 'postgresql-backup-and-recovery', title: 'PostgreSQL Backup & Recovery', category: 'PostgreSQL', excerpt: 'pg_dump, WAL archiving, PITR, and restore drills', skills: ['PostgreSQL', 'Database'], readMin: 11, content: 'Design a backup strategy you can actually restore. Use pg_dump and pg_dumpall for logical backups, continuous WAL archiving for point-in-time recovery, and rehearse restores on a staging cluster before you need them in an incident. Reference: https://www.postgresql.org/docs/current/backup.html' },
      { slug: 'javascript-async-patterns', title: 'JavaScript Async Patterns', category: 'JavaScript', excerpt: 'Promises, async/await, concurrency limits, and error handling', skills: ['JavaScript'], readMin: 10, content: 'Master asynchronous JavaScript with Promises and async/await. Handle errors with try/catch and Promise.allSettled, control concurrency to avoid overwhelming APIs, and understand the microtask queue for predictable ordering. Reference: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous' },
      { slug: 'nodejs-streams-in-practice', title: 'Node.js Streams in Practice', category: 'Node.js', excerpt: 'Backpressure, pipelines, and processing large files efficiently', skills: ['Node.js'], readMin: 11, content: 'Streams let Node.js process data larger than memory. Compose readable, writable and transform streams with pipeline(), respect backpressure instead of buffering everything, and handle errors so pipeline jobs clean up correctly. Reference: https://nodejs.org/api/stream.html' },
      { slug: 'typescript-strict-mode', title: 'TypeScript Strict Mode Deep Dive', category: 'TypeScript', excerpt: 'strictNullChecks, narrowing, and adopting strict mode safely', skills: ['TypeScript'], readMin: 10, content: 'Enable strict mode to catch real bugs at compile time. Adopt strictNullChecks and noImplicitAny incrementally, lean on discriminated unions and control-flow narrowing, and use unknown instead of any at API boundaries. Reference: https://www.typescriptlang.org/tsconfig#strict' },
      { slug: 'vue-state-management-pinia', title: 'Vue State Management with Pinia', category: 'Vue', excerpt: 'Stores, getters, actions, and SSR-safe state in Vue 3', skills: ['Vue', 'JavaScript'], readMin: 9, content: 'Pinia is the official state library for Vue 3. Define stores with setup syntax, expose typed getters and actions, compose stores for larger apps, and keep state SSR-safe by creating stores inside requests. Reference: https://pinia.vuejs.org/core-concepts/' },
      { slug: 'nextjs-data-fetching', title: 'Next.js Data Fetching Patterns', category: 'Next.js', excerpt: 'Server Components, caching, revalidation, and streaming', skills: ['Next.js', 'React'], readMin: 13, content: 'Choose the right data fetching strategy in the App Router. Fetch in Server Components by default, use tag-based revalidation for cached data, stream slow sections with Suspense, and move to Client Components only when interactivity demands it. Reference: https://nextjs.org/docs/app/building-your-application/data-fetching' },
      { slug: 'graphql-federation-scale', title: 'GraphQL Federation at Scale', category: 'GraphQL', excerpt: 'Composing subgraphs, entity keys, and query planning', skills: ['GraphQL', 'API'], readMin: 13, content: 'Federation splits one graph across teams. Model entities with @key, resolve references across subgraphs, and understand how the gateway plans queries so you avoid N+1 fan-out across services. Reference: https://www.apollographql.com/docs/federation/' },
      { slug: 'api-versioning-strategies', title: 'API Versioning Strategies', category: 'API', excerpt: 'URI, header and media-type versioning compared', skills: ['API', 'Backend'], readMin: 9, content: 'Version APIs deliberately. Compare URI versioning, custom headers and media types, prefer additive changes, and document deprecation timelines so clients can migrate without breaking production integrations. Reference: https://learn.microsoft.com/en-us/azure/architecture/best-practices/api-design' },
      { slug: 'jwt-refresh-token-rotation', title: 'JWT Refresh Token Rotation', category: 'Security', excerpt: 'Short-lived access tokens and detecting token replay', skills: ['Security', 'Node.js'], readMin: 11, content: 'Keep access tokens short-lived and rotate refresh tokens on every use. Store refresh token hashes server-side, detect replay of a rotated token as a compromise signal, and revoke the whole family when it happens. Reference: https://datatracker.ietf.org/doc/html/rfc6819' },
      { slug: 'react-state-management-guide', title: 'React State Management Guide', category: 'React', excerpt: 'Local state, context, and when to reach for a store', skills: ['React', 'JavaScript'], readMin: 12, content: 'Start with local state and lift only when needed. Use context for low-frequency global values, split contexts to limit re-renders, and adopt an external store only when server cache or complex cross-cutting state justifies it. Reference: https://react.dev/learn/managing-state' },
      { slug: 'css-container-queries', title: 'CSS Container Queries', category: 'CSS', excerpt: 'Component-level responsive design without media queries', skills: ['CSS'], readMin: 8, content: 'Container queries let components respond to their parent size instead of the viewport. Declare containment, write @container rules, and build reusable cards that adapt in sidebars, grids and modals alike. Reference: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_containment/Container_queries' },
      { slug: 'mongodb-data-modeling-patterns', title: 'MongoDB Data Modeling Patterns', category: 'MongoDB', excerpt: 'Embedding vs referencing, subsets, and schema validation', skills: ['MongoDB', 'Database'], readMin: 12, content: 'Model for how you read. Embed data accessed together, reference for many-to-many or unbounded growth, apply the subset pattern for large arrays, and enforce shape with JSON schema validation. Reference: https://www.mongodb.com/docs/manual/data-modeling/' },
      { slug: 'docker-multi-stage-builds', title: 'Docker Multi-Stage Builds', category: 'Docker', excerpt: 'Smaller, safer images with builder stages and caching', skills: ['Docker', 'DevOps'], readMin: 9, content: 'Multi-stage builds keep runtimes tiny. Compile in a builder stage, copy only artifacts into a slim runtime image, order layers for cache hits, run as a non-root user, and pin base image digests. Reference: https://docs.docker.com/build/building/multi-stage/' },
      { slug: 'aws-iam-best-practices', title: 'AWS IAM Best Practices', category: 'AWS', excerpt: 'Least privilege, roles, and permission boundaries', skills: ['AWS', 'Security'], readMin: 10, content: 'Grant least privilege and avoid long-lived keys. Prefer IAM roles for workloads, scope policies to specific ARNs and conditions, use permission boundaries for delegated administration, and review access with IAM Access Analyzer. Reference: https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html' },
      { slug: 'python-async-await-explained', title: 'Python Async/Await Explained', category: 'Python', excerpt: 'Event loops, coroutines, and concurrent I/O in Python', skills: ['Python'], readMin: 11, content: 'asyncio scales I/O-bound Python. Understand the event loop, await coroutines from async functions, run blocking calls in an executor, and use asyncio.gather with return_exceptions to handle partial failures. Reference: https://docs.python.org/3/library/asyncio.html' },
    ];

    const existingSlugs = new Set((await Blog.find({}, 'slug')).map((b) => b.slug));
    const missing = catalog.filter((b) => !existingSlugs.has(b.slug));
    if (missing.length) {
      await Blog.insertMany(missing);
      blogs = await Blog.find(filter).sort({ createdAt: -1 }).limit(200);
    }
  }
  
  res.json(blogs);
});

// Get single blog by slug
router.get('/blogs/:slug', async (req, res) => {
  try {
    const blog = await Blog.findOne({ slug: req.params.slug });
    if (!blog) return res.status(404).json({ message: 'Blog not found' });
    res.json(blog);
  } catch (error) {
    res.status(500).json({ message: 'Server Error' });
  }
});

export default router;
